package com.ace.converter.extentions

import com.ace.converter.model.ModelResponce


fun ModelResponce.getCurrency(currency: String): Float {
    return when (currency) {
        "EUR_RUB" -> EUR_RUB
        "EUR_USD" -> EUR_USD
        "USD_RUB" -> USD_RUB
        "USD_EUR" -> USD_EUR
        "RUB_EUR" -> RUB_EUR
        "RUB_USD" -> RUB_USD
        "BTC_USD" -> BTC_USD
        "BTC_EUR" -> BTC_EUR
        "BTC_RUB" -> BTC_RUB
        "USD_BTC" -> USD_BTC
        "EUR_BTC" -> EUR_BTC
        "RUB_BTC" -> RUB_BTC
        "UAH_BTC" -> UAH_BTC
        "UAH_USD" -> UAH_USD
        "UAH_EUR" -> UAH_EUR
        "UAH_RUB" -> UAH_RUB
        "BTC_UAH" -> BTC_UAH
        "USD_UAH" -> USD_UAH
        "EUR_UAH" -> EUR_UAH
        "RUB_UAH" -> RUB_UAH
        "CHF_BTC" -> CHF_BTC
        "CHF_USD" -> CHF_USD
        "CHF_EUR" -> CHF_EUR
        "CHF_RUB" -> CHF_RUB
        "CHF_UAH" -> CHF_UAH
        "BTC_CHF" -> BTC_CHF
        "USD_CHF" -> USD_CHF
        "EUR_CHF" -> EUR_CHF
        "RUB_CHF" -> RUB_CHF
        "UAH_CHF" -> UAH_CHF
        "CNY_BTC" -> CNY_BTC
        "CNY_USD" -> CNY_USD
        "CNY_EUR" -> CNY_EUR
        "CNY_RUB" -> CNY_RUB
        "CNY_UAH" -> CNY_UAH
        "CNY_CHF" -> CNY_CHF
        "BTC_CNY" -> BTC_CNY
        "USD_CNY" -> USD_CNY
        "EUR_CNY" -> EUR_CNY
        "RUB_CNY" -> RUB_CNY
        "UAH_CNY" -> UAH_CNY
        "CHF_CNY" -> CHF_CNY
        "CZK_BTC" -> CZK_BTC
        "CZK_USD" -> CZK_USD
        "CZK_EUR" -> CZK_EUR
        "CZK_RUB" -> CZK_RUB
        "CZK_UAH" -> CZK_UAH
        "CZK_CHF" -> CZK_CHF
        "CZK_CNY" -> CZK_CNY
        "BTC_CZK" -> BTC_CZK
        "USD_CZK" -> USD_CZK
        "EUR_CZK" -> EUR_CZK
        "RUB_CZK" -> RUB_CZK
        "UAH_CZK" -> UAH_CZK
        "CHF_CZK" -> CHF_CZK
        "CNY_CZK" -> CNY_CZK
        "INR_BTC" -> INR_BTC
        "INR_USD" -> INR_USD
        "INR_EUR" -> INR_EUR
        "INR_RUB" -> INR_RUB
        "INR_UAH" -> INR_UAH
        "INR_CHF" -> INR_CHF
        "INR_CNY" -> INR_CNY
        "INR_CZK" -> INR_CZK
        "BTC_INR" -> BTC_INR
        "USD_INR" -> USD_INR
        "EUR_INR" -> EUR_INR
        "RUB_INR" -> RUB_INR
        "UAH_INR" -> UAH_INR
        "CHF_INR" -> CHF_INR
        "CNY_INR" -> CNY_INR
        "CZK_INR" -> CZK_INR
        "XAG_BTC" -> XAG_BTC
        "XAG_USD" -> XAG_USD
        "XAG_EUR" -> XAG_EUR
        "XAG_RUB" -> XAG_RUB
        "XAG_UAH" -> XAG_UAH
        "XAG_CHF" -> XAG_CHF
        "XAG_CNY" -> XAG_CNY
        "XAG_CZK" -> XAG_CZK
        "XAG_INR" -> XAG_INR
        "BTC_XAG" -> BTC_XAG
        "USD_XAG" -> USD_XAG
        "EUR_XAG" -> EUR_XAG
        "RUB_XAG" -> RUB_XAG
        "UAH_XAG" -> UAH_XAG
        "CHF_XAG" -> CHF_XAG
        "CNY_XAG" -> CNY_XAG
        "CZK_XAG" -> CZK_XAG
        "INR_XAG" -> INR_XAG
        else -> 1.0f
    }
}