package com.ace.converter.model

class ModelResponce(
    var EUR_RUB: Float,
    var RUB_EUR: Float,
    var USD_RUB: Float,
    var RUB_USD: Float,
    var USD_EUR: Float,
    var EUR_USD: Float,
    //BTC
    var BTC_USD: Float,
    var BTC_EUR: Float,
    var BTC_RUB: Float,
    var USD_BTC: Float,
    var EUR_BTC: Float,
    var RUB_BTC: Float,
    //UAH
    var UAH_BTC: Float,
    var UAH_USD: Float,
    var UAH_EUR: Float,
    var UAH_RUB: Float,
    var BTC_UAH: Float,
    var USD_UAH: Float,
    var EUR_UAH: Float,
    var RUB_UAH: Float,
    //CHF
    var CHF_BTC: Float,
    var CHF_USD: Float,
    var CHF_EUR: Float,
    var CHF_RUB: Float,
    var CHF_UAH: Float,
    var BTC_CHF: Float,
    var USD_CHF: Float,
    var EUR_CHF: Float,
    var RUB_CHF: Float,
    var UAH_CHF: Float,
    //CNY
    var CNY_BTC: Float,
    var CNY_USD: Float,
    var CNY_EUR: Float,
    var CNY_RUB: Float,
    var CNY_UAH: Float,
    var CNY_CHF: Float,
    var BTC_CNY: Float,
    var USD_CNY: Float,
    var EUR_CNY: Float,
    var RUB_CNY: Float,
    var UAH_CNY: Float,
    var CHF_CNY: Float,
    //CZK
    var CZK_BTC: Float,
    var CZK_USD: Float,
    var CZK_EUR: Float,
    var CZK_RUB: Float,
    var CZK_UAH: Float,
    var CZK_CHF: Float,
    var CZK_CNY: Float,
    var BTC_CZK: Float,
    var USD_CZK: Float,
    var EUR_CZK: Float,
    var RUB_CZK: Float,
    var UAH_CZK: Float,
    var CHF_CZK: Float,
    var CNY_CZK: Float,
    //INR
    var INR_BTC: Float,
    var INR_USD: Float,
    var INR_EUR: Float,
    var INR_RUB: Float,
    var INR_UAH: Float,
    var INR_CHF: Float,
    var INR_CNY: Float,
    var INR_CZK: Float,
    var BTC_INR: Float,
    var USD_INR: Float,
    var EUR_INR: Float,
    var RUB_INR: Float,
    var UAH_INR: Float,
    var CHF_INR: Float,
    var CNY_INR: Float,
    var CZK_INR: Float,
    //XAG
    var XAG_BTC: Float,
    var XAG_USD: Float,
    var XAG_EUR: Float,
    var XAG_RUB: Float,
    var XAG_UAH: Float,
    var XAG_CHF: Float,
    var XAG_CNY: Float,
    var XAG_CZK: Float,
    var XAG_INR: Float,
    var BTC_XAG: Float,
    var USD_XAG: Float,
    var EUR_XAG: Float,
    var RUB_XAG: Float,
    var UAH_XAG: Float,
    var CHF_XAG: Float,
    var CNY_XAG: Float,
    var CZK_XAG: Float,
    var INR_XAG: Float
)

